# Generated by Django 4.2.11 on 2025-02-19 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionlisting_comment_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='image',
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='imageURL',
            field=models.URLField(blank=True, null=True),
        ),
    ]
