# Generated by Django 4.2.11 on 2025-03-03 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_alter_comment_auction_listing_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commenter',
            new_name='commenter_id',
        ),
    ]
