# Generated by Django 4.2.11 on 2025-03-03 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_rename_commenter_comment_commenter_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='price',
            new_name='start_bid',
        ),
    ]
