# Generated by Django 4.2.11 on 2025-03-11 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_rename_price_auctionlisting_start_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='category',
            field=models.CharField(choices=[('', '--please choose a category--'), ('1', 'Antiques & Arts'), ('2', 'Books'), ('3', 'CDs, DVD & Video Games'), ('4', 'Clothing & Accessories'), ('5', 'Computer & Electronics'), ('6', 'Food, Wine & Gourmet Itmes'), ('7', 'Golf & Sports Gear'), ('8', 'Handbags & Jewelry'), ('9', 'Health & Fitness'), ('10', 'Auto'), ('11', 'Home & Garden'), ('12', 'Toys')], max_length=50),
        ),
    ]
