# Generated by Django 4.2.11 on 2025-03-12 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_alter_auctionlisting_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='category',
            field=models.CharField(choices=[(None, '--please choose a category--'), ('antique_and_arts', 'Antiques & Arts'), ('books', 'Books'), ('cds_dvs_video_games', 'CDs, DVD & Video Games'), ('clothing_and_accessories', 'Clothing & Accessories'), ('computer_and_electronics', 'Computer & Electronics'), ('smartphone_and_tablets', 'Smartphones & Tablets'), ('food_wine_and_gourmet', 'Food, Wine & Gourmet Itmes'), ('golf_and_sport_gear', 'Golf & Sports Gear'), ('handbags_and_jewelry', 'Handbags & Jewelry'), ('health_and_fitness', 'Health & Fitness'), ('auto', 'Auto'), ('home_and_garden', 'Home & Garden'), ('toys', 'Toys')], max_length=50),
        ),
    ]
