# Generated by Django 4.2.11 on 2025-03-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_alter_auctionlisting_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
