# Generated by Django 4.2.11 on 2025-03-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_alter_auctionlisting_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
