# Generated by Django 4.2.11 on 2025-03-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_alter_auctionlisting_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='imageURL',
            field=models.URLField(),
        ),
    ]
