# Generated by Django 4.2.11 on 2025-03-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_alter_auctionlisting_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='auction_title',
            field=models.CharField(max_length=100),
        ),
    ]
